from turtle import Turtle, Screen

elsa = Turtle()
elsa.shape("turtle")
elsa.speed("fast")

window = Screen()
window.setup(1000,500)

window.bgcolor('white')

elsa.setpos(0,0)
elsa.pensize(10)
elsa.pendown()
elsa.pencolor("black")
elsa.circle(80)
print(elsa.pos())
elsa.penup()
elsa.setpos(-180,0)
elsa.pendown()
elsa.pencolor("blue")
elsa.circle(80)
print(elsa.pos())
elsa.penup()
elsa.setpos(+180,0)
elsa.pendown()
elsa.pencolor("red")
elsa.circle(80)
print(elsa.pos())
elsa.penup()
elsa.setpos(90,-90)
elsa.pendown()
elsa.pencolor("lime")
elsa.circle(80)
print(elsa.pos())
elsa.penup()
elsa.setpos(-90,-90)
elsa.pendown()
elsa.pencolor("yellow")
elsa.circle(80)
print(elsa.pos())
elsa.penup()
elsa.hideturtle()
